config/routes.rb
Rails.application.routes.draw do

 root 'companies#index'

 resources :companies do

   resources :events

 end


end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :events

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :company

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index

    @companies = Company.all

  end

  def new

    @company = Company.new


  end

  def create

    @company = Company.create(company_params)
    @company.save
    redirect_to companies_path

  end

  def edit

    @company = Company.find(params[:id])
    @event = @company.events.new
    @event_all = @company.events.all

  end


  def update

    @company = Company.find(params[:id])
    @company.update(company_params)
    redirect_to edit_company_path(@company[:id])

  end

  def destroy

    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path

  end


  private

  def company_params

  params.require(:company).permit(:name)

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def create

    @event = Event.create(event_params)
    @event[:company_id] = params[:company_id]
    @event.save
    redirect_to edit_company_path(@event[:company_id])

  end

  def edit
    @event = Event.find(params[:id])
    @company = Company.find(params[:company_id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to edit_company_path(@event[:company_id])
  end

  private

  def event_params

  params.require(:event).permit(:name)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/edit.html.erb
<%= link_to " Back to Companies", companies_path %>
<p>

</p>
<%= form_for @company do |t| %>

<%= t.label :name, "Company Name" %>
<%= t.text_field :name %>
<%= t.submit %>

<% end %>
<p></p>

<%= form_for [@company, @event] do |t| %>
<%= t.label :name, "Event Name" %>
<%= t.text_field :name %>
<%= t.submit %>

<% end %>
<h2>List of Events</h2>
<p></p>

  <% @event_all.each do |event| %>
    <p></p>

  <%= link_to event.name, edit_company_event_path(@company[:id], event[:id]) %>
    <p></p>

<% end %>

app/views/companies/index.html.erb
<%= link_to "New Company", new_company_path %>
<h2>Company List</h2>
<% @companies.each do |company| %>
  <div class="row">
    <p>
    </p>
      <%= link_to company.name, edit_company_path(company[:id]) %>
      <%= "        "  %>
      <%= link_to "Delete this company", company_path(company[:id]), method: :delete %>
  </div>
    <p>
    </p>
  _____________________________________________________
<% end %>

app/views/companies/new.html.erb
<%= form_for @company do |t| %>

<%= t.label :name %>
<%= t.text_field :name %>
<%= t.submit %>
<% end %>

app/views/events/edit.html.erb
<%= link_to " Back to Companies", companies_path %>
<p>

</p>

<%= form_for [@company, @event] do |t| %>

<%= t.label :name, "Edit Event Name" %>
<%= t.text_field :name %>
<%= t.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventCompanies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>